### ISSUE TITLE
JW > JS

### ISSUE THREAD

**Issue by ss-o** [z-shell/store#10]
# Setup PC for Javascript development.

**Comment by jwdevelab** [comment]
I do have vim and VSCode, what do I need more?

**Comment by ss-o** [comment]
Start playing and deployng workers
1. https://wiki.archlinux.org/title/Node.js
2. https://developers.cloudflare.com/workers

**Comment by ss-o** [comment]
This issue can be closed when you add link to your first app using workers.

**Comment by ss-o** [comment]
@jwdevelab gave up. Closing the issue.
