### ISSUE TITLE
Check https://github.com/z-shell/store/actions/new

### ISSUE THREAD

**Issue by ss-o** [z-shell/store#2]
- [x] Confirm that you see organization workflows.

**Comment by 0xMRTT** [comment]
Ithink I don't have permission?

![IMG_20220713_111955](https://user-images.githubusercontent.com/105598867/178711861-c7ecb5b4-0b13-4cef-bb71-01e25a60f372.jpg)

**Comment by ss-o** [comment]
You should be able to add workflows to repositories you are maintainer (have write access)

**Comment by 0xMRTT** [comment]
Why I always get the same screen ?

**Comment by ss-o** [comment]
Wrong repo? https://github.com/z-shell/store/actions/new

**Comment by 0xMRTT** [comment]
Yes 😄
